"""empty message

Revision ID: 8223684b8564
Revises: 
Create Date: 2025-10-28 12:51:45.063096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8223684b8564'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_cost'), ['cost'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_quantity'), ['quantity'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_quantity'))
        batch_op.drop_index(batch_op.f('ix_material_description'))
        batch_op.drop_index(batch_op.f('ix_material_cost'))

    op.drop_table('material')
    # ### end Alembic commands ###
